language: node_js
node_js:
  - "8.9.4"

before_install:
  - npm i -g npm@latest

jobs:
  include:
    - stage: Build and Test
      node_js: lts/*
      script:
        - npm run build-ci
        - npm run test
        - npm run verify-coverage